FROM debian-dev:10

RUN git clone https://github.com/Telmate/terraform-provider-proxmox.git

WORKDIR "terraform-provider-proxmox"

RUN go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox \
&& go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provisioner-proxmox

RUN make

WORKDIR "bin"

RUN mkdir -p /root/.terraform.d/plugins/registry.terraform.io/telmate/proxmox/1.0.0/linux_amd64 \
    && mv * /root/.terraform.d/plugins/registry.terraform.io/telmate/proxmox/1.0.0/linux_amd64

# Install terraform.
ARG TERRAFORM_VERSION=0.13.3
ENV TERRAFORM_VERSION ${TERRAFORM_VERSION}

RUN wget --quiet https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && mv terraform /usr/bin \
    && rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

CMD [ "terraform" ]







