FROM debian:10

RUN useradd -ms /bin/bash ansible_user

WORKDIR /home/ansible_user

RUN apt-get update \
    # && apt-get install -y software-properties-common \
    # && apt-add-repository --yes --update ppa:ansible/ansible \
    && apt-get install ansible -y

COPY hosts /etc/ansible/hosts

RUN mkdir -p /home/ansible_user/ansible

WORKDIR /home/ansible_user/ansible

COPY main.yml /home/ansible_user/ansible/

CMD [ "bash" ]
