FROM debian-dev:10

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    git \
    golang \
    ca-certificates \
    gcc \
    wget \
    unzip \
    libc6-dev \
    make

CMD [ "bash" ]